name: CI/CD - FIS BookHub Grupo6

on:
  push:
    branches:
      - grupo6
  pull_request:
    branches:
      - grupo6

jobs:
  build-test-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v3

      - name: Configurar Node.js (cambia si usas otro lenguaje)
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Instalar dependencias
        run: npm install

      - name: Build del proyecto
        run: npm run build

      - name: Ejecutar pruebas unitarias
        run: npm test

