name: CI/CD

on:
  push:
    branches:
      - Grupo#5
  pull_request:
    branches:
      - Grupo#5
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v3

      - name: Configurar JDK 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Construcción del proyecto
        run: mvn clean package

      - name: Ejecutar pruebas
        run: mvn test

      - name: Subir artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: target/*.jar
