name: CI Grupo3 - Maven Build

on:
  push:
    branches:
      - Grupo3

jobs:
  build:
    runs-on: ubuntu-latest


    steps:
      # 1. Clonar el repositorio
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      # 2. Configurar JDK (versión estándar para proyectos modernos)
      - name: Configurar JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. Compilar el proyecto
      - name: Compilar con Maven
        run: mvn compile

      # 4. Ejecutar pruebas unitarias
      - name: Ejecutar pruebas con Maven
        run: mvn test
